// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwkgbmCje7mJSQ6aT9AUfiiUPgEqcF4FA',
    appId: '1:216296260271:web:bf7cf3334f5d1f4458ca5a',
    messagingSenderId: '216296260271',
    projectId: 'virtual-student-advisor-b5ce2',
    authDomain: 'virtual-student-advisor-b5ce2.firebaseapp.com',
    storageBucket: 'virtual-student-advisor-b5ce2.appspot.com',
    measurementId: 'G-FPE7MVY6HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAYRHn-p3m_VoPw0v1dxGbrlV8gTWc6gA',
    appId: '1:216296260271:android:e612e214e236d74758ca5a',
    messagingSenderId: '216296260271',
    projectId: 'virtual-student-advisor-b5ce2',
    storageBucket: 'virtual-student-advisor-b5ce2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxDlzFpJGxuT9i97mD6A_wEhjWmCi3x2Y',
    appId: '1:216296260271:ios:936416b4ecfc5aa158ca5a',
    messagingSenderId: '216296260271',
    projectId: 'virtual-student-advisor-b5ce2',
    storageBucket: 'virtual-student-advisor-b5ce2.appspot.com',
    iosBundleId: 'com.example.buVsa',
  );
}
